// <auto-generated />
namespace BusinessManager.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ResetLayawayAndInvoiceFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResetLayawayAndInvoiceFK));
        
        string IMigrationMetadata.Id
        {
            get { return "201910062104138_ResetLayawayAndInvoiceFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
